language: r

warnings_are_errors: false

r_packages: 
  - RSelenium
  - testthat
  - XML

os:
  - linux
  - osx

osx_image: xcode12.5

sudo: false

cache: packages

addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev